import StyledarkSizemediumState1 from "../components/styledark-sizemedium-state1";
import StyledarkSizemediumState from "../components/styledark-sizemedium-state";
import StyledarkSizemediumState2 from "../components/styledark-sizemedium-state2";

const Button = () => {
  return (
    <div className="relative rounded-[5px] box-border w-full h-[552px] overflow-hidden border-[1px] border-dashed border-primary-2">
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled.svg"
        propTop="124px"
        propLeft="162px"
        propBackgroundColor="unset"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), #3772ff"
        propBorder="unset"
        propColor="#fcfcfd"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled.svg"
        propTop="184px"
        propLeft="162px"
        propBackgroundColor="unset"
        propPadding="12px 16px"
        propOpacity="0.5"
        propBackground="linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), #3772ff"
        propBorder="unset"
        propColor="#fcfcfd"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled.svg"
        propTop="124px"
        propLeft="288px"
        propBackgroundColor="unset"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), #3772ff"
        propBorder="unset"
        propColor="#fcfcfd"
        propTextAlign="left"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled.svg"
        propTop="184px"
        propLeft="288px"
        propBackgroundColor="unset"
        propPadding="12px 16px"
        propOpacity="0.5"
        propBackground="linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), #3772ff"
        propBorder="unset"
        propColor="#fcfcfd"
        propTextAlign="left"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled.svg"
        propTop="64px"
        propLeft="158px"
        propBackgroundColor="#3772ff"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled.svg"
        propTop="64px"
        propLeft="284px"
        propBackgroundColor="#3772ff"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
        propTextAlign="left"
      />
      <StyledarkSizemediumState2
        propTop="124px"
        propLeft="64px"
        propBackgroundColor="unset"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), #3772ff"
        propBorder="unset"
        propColor="#fcfcfd"
        label="Button"
      />
      <StyledarkSizemediumState2
        propTop="184px"
        propLeft="64px"
        propBackgroundColor="unset"
        propPadding="12px 16px"
        propOpacity="0.5"
        propBackground="linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), #3772ff"
        propBorder="unset"
        propColor="#fcfcfd"
        label="Button"
      />
      <StyledarkSizemediumState2
        propTop="64px"
        propLeft="60px"
        propBackgroundColor="#3772ff"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
        label="Button"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled.svg"
        propTop="124px"
        propLeft="512px"
        propBackgroundColor="#23262f"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled.svg"
        propTop="184px"
        propLeft="512px"
        propBackgroundColor="#23262f"
        propPadding="12px 16px"
        propOpacity="0.5"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled.svg"
        propTop="124px"
        propLeft="638px"
        propBackgroundColor="#23262f"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
        propTextAlign="right"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled.svg"
        propTop="184px"
        propLeft="638px"
        propBackgroundColor="#23262f"
        propPadding="12px 16px"
        propOpacity="0.5"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
        propTextAlign="right"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled1.svg"
        propTop="64px"
        propLeft="512px"
        propBackgroundColor="unset"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="2px solid #e6e8ec"
        propColor="#23262f"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled1.svg"
        propTop="64px"
        propLeft="638px"
        propBackgroundColor="unset"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="2px solid #e6e8ec"
        propColor="#23262f"
        propTextAlign="right"
      />
      <StyledarkSizemediumState2
        propTop="124px"
        propLeft="414px"
        propBackgroundColor="#23262f"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
        label="Button"
      />
      <StyledarkSizemediumState2
        propTop="184px"
        propLeft="414px"
        propBackgroundColor="#23262f"
        propPadding="12px 16px"
        propOpacity="0.5"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
        label="Button"
      />
      <StyledarkSizemediumState2
        propTop="64px"
        propLeft="414px"
        propBackgroundColor="unset"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="2px solid #e6e8ec"
        propColor="#23262f"
        label="Button"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled1.svg"
        propTop="124px"
        propLeft="862px"
        propBackgroundColor="#fcfcfd"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#23262f"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled1.svg"
        propTop="184px"
        propLeft="862px"
        propBackgroundColor="#fcfcfd"
        propPadding="12px 16px"
        propOpacity="0.5"
        propBackground="unset"
        propBorder="unset"
        propColor="#23262f"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled1.svg"
        propTop="124px"
        propLeft="988px"
        propBackgroundColor="#fcfcfd"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#23262f"
        propTextAlign="right"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled1.svg"
        propTop="184px"
        propLeft="988px"
        propBackgroundColor="#fcfcfd"
        propPadding="12px 16px"
        propOpacity="0.5"
        propBackground="unset"
        propBorder="unset"
        propColor="#23262f"
        propTextAlign="right"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled.svg"
        propTop="64px"
        propLeft="862px"
        propBackgroundColor="unset"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="2px solid #777e91"
        propColor="#fcfcfd"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled.svg"
        propTop="64px"
        propLeft="988px"
        propBackgroundColor="unset"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="2px solid #777e91"
        propColor="#fcfcfd"
        propTextAlign="right"
      />
      <StyledarkSizemediumState2
        propTop="124px"
        propLeft="764px"
        propBackgroundColor="#fcfcfd"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#23262f"
        label="Button"
      />
      <StyledarkSizemediumState2
        propTop="184px"
        propLeft="764px"
        propBackgroundColor="#fcfcfd"
        propPadding="12px 16px"
        propOpacity="0.5"
        propBackground="unset"
        propBorder="unset"
        propColor="#23262f"
        label="Button"
      />
      <StyledarkSizemediumState2
        propTop="64px"
        propLeft="764px"
        propBackgroundColor="unset"
        propPadding="12px 16px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="2px solid #777e91"
        propColor="#fcfcfd"
        label="Button"
      />
      <StyledarkSizemediumState2
        propTop="304px"
        propLeft="60px"
        propBackgroundColor="#3772ff"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
        label="Button"
      />
      <StyledarkSizemediumState2
        propTop="372px"
        propLeft="60px"
        propBackgroundColor="unset"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), #3772ff"
        propBorder="unset"
        propColor="#fcfcfd"
        label="Button"
      />
      <StyledarkSizemediumState2
        propTop="440px"
        propLeft="60px"
        propBackgroundColor="unset"
        propPadding="16px 24px"
        propOpacity="0.5"
        propBackground="linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), #3772ff"
        propBorder="unset"
        propColor="#fcfcfd"
        label="Button"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled.svg"
        propTop="304px"
        propLeft="181px"
        propBackgroundColor="#3772ff"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled.svg"
        propTop="304px"
        propLeft="330px"
        propBackgroundColor="#3772ff"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
        propTextAlign="right"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled.svg"
        propTop="372px"
        propLeft="181px"
        propBackgroundColor="unset"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), #3772ff"
        propBorder="unset"
        propColor="#fcfcfd"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled.svg"
        propTop="440px"
        propLeft="181px"
        propBackgroundColor="unset"
        propPadding="16px 24px"
        propOpacity="0.5"
        propBackground="linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), #3772ff"
        propBorder="unset"
        propColor="#fcfcfd"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled.svg"
        propTop="372px"
        propLeft="330px"
        propBackgroundColor="unset"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), #3772ff"
        propBorder="unset"
        propColor="#fcfcfd"
        propTextAlign="right"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled.svg"
        propTop="440px"
        propLeft="330px"
        propBackgroundColor="unset"
        propPadding="16px 24px"
        propOpacity="0.5"
        propBackground="linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), #3772ff"
        propBorder="unset"
        propColor="#fcfcfd"
        propTextAlign="right"
      />
      <StyledarkSizemediumState2
        propTop="304px"
        propLeft="479px"
        propBackgroundColor="unset"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="2px solid #e6e8ec"
        propColor="#23262f"
        label="Button"
      />
      <StyledarkSizemediumState2
        propTop="372px"
        propLeft="479px"
        propBackgroundColor="#23262f"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
        label="Button"
      />
      <StyledarkSizemediumState2
        propTop="440px"
        propLeft="479px"
        propBackgroundColor="#23262f"
        propPadding="16px 24px"
        propOpacity="0.5"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
        label="Button"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled1.svg"
        propTop="304px"
        propLeft="600px"
        propBackgroundColor="unset"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="2px solid #e6e8ec"
        propColor="#23262f"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled1.svg"
        propTop="304px"
        propLeft="749px"
        propBackgroundColor="unset"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="2px solid #e6e8ec"
        propColor="#23262f"
        propTextAlign="right"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled.svg"
        propTop="372px"
        propLeft="600px"
        propBackgroundColor="#23262f"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled.svg"
        propTop="440px"
        propLeft="600px"
        propBackgroundColor="#23262f"
        propPadding="16px 24px"
        propOpacity="0.5"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled.svg"
        propTop="372px"
        propLeft="749px"
        propBackgroundColor="#23262f"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
        propTextAlign="right"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled.svg"
        propTop="440px"
        propLeft="749px"
        propBackgroundColor="#23262f"
        propPadding="16px 24px"
        propOpacity="0.5"
        propBackground="unset"
        propBorder="unset"
        propColor="#fcfcfd"
        propTextAlign="right"
      />
      <StyledarkSizemediumState2
        propTop="304px"
        propLeft="898px"
        propBackgroundColor="unset"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="2px solid #777e91"
        propColor="#fcfcfd"
        label="Button"
      />
      <StyledarkSizemediumState2
        propTop="372px"
        propLeft="898px"
        propBackgroundColor="#fcfcfd"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#23262f"
        label="Button"
      />
      <StyledarkSizemediumState2 label="Button" />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled.svg"
        propTop="304px"
        propLeft="1012px"
        propBackgroundColor="unset"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="2px solid #777e91"
        propColor="#fcfcfd"
      />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled.svg"
        propTop="304px"
        propLeft="1154px"
        propBackgroundColor="unset"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="2px solid #777e91"
        propColor="#fcfcfd"
        propTextAlign="right"
      />
      <StyledarkSizemediumState1
        iconId="/iconsstarfilled1.svg"
        propTop="372px"
        propLeft="1012px"
        propBackgroundColor="#fcfcfd"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#23262f"
      />
      <StyledarkSizemediumState1 iconId="/iconsstarfilled1.svg" />
      <StyledarkSizemediumState
        iconId="/iconsstarfilled1.svg"
        propTop="372px"
        propLeft="1154px"
        propBackgroundColor="#fcfcfd"
        propPadding="16px 24px"
        propOpacity="unset"
        propBackground="unset"
        propBorder="unset"
        propColor="#23262f"
        propTextAlign="right"
      />
      <StyledarkSizemediumState iconId="/iconsstarfilled1.svg" />
    </div>
  );
};

export default Button;
